version: '3'
services:
  backend:
    container_name: dndnearby-backend
    build:
      context: ./application
      dockerfile: dockerfile-backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./application:/app
  db:
    container_name: dndnearby-db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    container_name: dndnearby-redis
    image: redis
    ports:
      - 6379:6379
volumes:
  postgres-data: {}

